### ISSUE TITLE
Form don't have a welcome screen then method GetForm crash

### ISSUE THREAD

**Issue by VictoRD11** [adamaveray/typeform#8]
Hello @adamaveray!
Some forms do not have a welcome screen, and then the method(GetForm) crashes :(

```
Undefined array key "welcome_screens" {"userId":11111,"exception":"[object] (ErrorException(code: 0): Undefined array key \"welcome_screens\" at /var/www/app/vendor/adamaveray/typeform/src/Models/Forms/Form.php:59)

[stacktrace] 
#0 /var/www/app/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(266): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Undefined array...', '/var/www/app/ve...', 59) 
#1 /var/www/app/vendor/adamaveray/typeform/src/Models/Forms/Form.php(59): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}(2, 'Undefined array...', '/var/www/app/ve...', 59) 
#2 /var/www/app/vendor/adamaveray/typeform/src/ApiClient.php(295): AdamAveray\\Typeform\\Models\\Forms\\Form->__construct(Array) 
#3 /var/www/app/app/Services/Api/Typeform/TypeformFormsService.php(31): AdamAveray\\Typeform\\ApiClient->getForm('******') 
#4 /var/www/app/app/Jobs/Api/Typeform/SyncForm.php(39): Softserve\\Services\\Api\\Typeform\\TypeformFormsService->syncForms(Object(Softserve\\Entities\\Typeform\\Workspace), 200)
```

Can you fix this problem? Thanks for the Wrapper Library 💙💛

**Comment by adamaveray** [comment]
v1.1.6 released with this fix: https://packagist.org/packages/adamaveray/typeform#1.1.6
